### PR TITLE
Fix imports in TypeScript

### LINKED ISSUE #38: Import SEO component doesn't pass astro check
In a fresh and empty project (with `astro-seo` version `^0.5.0` installed), running `astro check` will fail if you include `astro-seo` as the documentation states.

```
---
import { SEO } from "astro-seo";
---
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width" />

		<SEO
			title="A Very Descriptive Title"
			description="A heavily optimized description full of well-researched keywords." />
	</head>
	<body>
		<h1>Astro</h1>
	</body>
</html>
```

```
> @example/minimal@0.0.1 check
> astro check

src/pages/index.astro:1:20 - Cannot find module 'astro-seo' or its corresponding type declarations.
1  import { SEO } from "astro-seo";
                       ~~~~~~~~~~~

Found 1 errors.
```

### PR DESCRIPTION
**Pull request by alex-grover**
## Description

Fixes #38 by adding an index file in the root directory, and converting the existing index file to `.ts`. This is the pattern used in the [community template](https://github.com/astro-community/component-template). It looks like the [official template](https://github.com/withastro/astro/tree/main/examples/component/packages/my-component) uses an `index.js`, but that seems not to work if you try to import types from that file.

A few other small changes:
- Fix malformed `package.json` introduced by #40
- Also export `*` from `SEO.astro` so consumers can import Props for typing

## Testing

- [x] Test locally in a real project using `npm link`
- [x] Cypress tests still pass
- [x] `npm run check` has same output

### CODE REVIEW

**Comment by alex-grover** [comment]
@jonasmerlin if you're open to it, I can also add a CI job so issues like the package.json typo get caught in the PR. let me know!

**Comment by jonasmerlin** [comment]
@alex-grover Whoa, nice work! Thank you so much for looking into this. Always glad to accept help from a fellow Colemak-DH user. 😁 

The CI job would be super helpful as well. Sadly I don't have much time to maintain this project beyond accepting PRs etc. So anything that catches things early is very welcome.

I will merge this and you create a separate PR for the CI, alright?

**Comment by alex-grover** [comment]
sounds good!
